#pragma config(Motor,  port1,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightMotor] = 127;
motor[leftMotor] = 127;
wait1Msec(20000);
}
